name: Docker

on:
  push:
    branches:
      - main
  schedule:
    - cron: "11 1 * * 1,3,5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: ./sources.sh

      - run: ./build.sh
